<!doctype html>
<html lang="en" prefix="op: http://media.facebook.com/op#">
  <head>
    <meta charset="utf-8">
    <!-- URL of the web version of this article -->
    <link rel="canonical" href="http://example.com/article.html">
    <meta property="op:markup_version" content="v1.0">
  </head>
  <body>
    <article>
      <header>
        <!-- The title and subtitle shown in your Instant Article -->
        <h1>Article Title</h1>
        <h2>Article Subtitle</h2>

        <!-- The date and time when your article was originally published -->
        <time class="op-published" datetime="2014-11-11T04:44:16Z">November 11th, 4:44 PM</time>

        <!-- The date and time when your article was last updated -->
        <time class="op-modified" dateTime="2014-12-11T04:44:16Z">December 11th, 4:44 PM</time>

        <!-- The authors of your article -->
        <address>
          <a rel="facebook" href="http://facebook.com/brandon.diamond">Brandon Diamond</a>
          Brandon is an avid zombie hunter.
        </address>
        <address>
          <a>TR Vishwanath</a>
          Vish is a scholar and a gentleman.
        </address>

        <!-- The cover image shown inside your article --> 
        <figure>
          <img src="http://mydomain.com/path/to/img.jpg" />
          <figcaption>This image is amazing</figcaption>
        </figure>   

        <!-- A kicker for your article --> 
        <h3 class="op-kicker">
          This is a kicker
        </h3>        

      </header>

      <!-- Article body goes here -->

      <!-- Body text for your article -->
      <p> Article content </p> 

      <!-- A video within your article -->
      <figure>
        <video>
          <source src="http://mydomain.com/path/to/video.mp4" type="video/mp4" />
        </video>
      </figure>

      <!-- An ad within your article -->
      <figure class="op-ad">
        <iframe src="https://www.adserver.com/ss;adtype=banner320x50" height="60" width="320"></iframe>
      </figure>

      <!-- Analytics code for your article -->
      <figure class="op-tracker">
          <iframe src="" hidden></iframe>
      </figure>

      <footer>
        <!-- Credits for your article -->
        <aside>Acknowledgements</aside>

        <!-- Copyright details for your article -->
        <small>Legal notes</small>
      </footer>
    </article>
  </body>
</html>

<?php
/**
 * Copyright (c) 2017-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */
require_once __DIR__ . '/../vendor/autoload.php';
use Facebook\InstantArticles\AMP\AMPArticle;
// Load instant article file into string
$instant_article_string = file_get_contents(__DIR__.'/instant-article-example.html');
// Instant articles have no width and height information for images and video on
// it's markup but the AMP spec requires everything to have explicit sizing.
// This will hold our custom properties
$properties = array();
// Videos require explicit sizing, if you fail to provide it, the default values
// may distort your Videos
$properties[AMPArticle::MEDIA_SIZES_KEY]
  ['http://mydomain.com/path/to/video.mp4'] = array(320, 240);
// Images can also be passed
// IMPORTANT: The image will not have fixed-width, but it will respect the
//            aspect ration provided here. They are using the responsive layout
$properties[AMPArticle::MEDIA_SIZES_KEY]
  ['http://mydomain.com/path/to/crazy.jpg'] = array(640, 480);
// The SDK can automatically download the images and get their sizes if they are not
// in the array above, if you enable the following option.
//
// WARNING: THIS MAY LEAD TO EXCESSIVE DOWNLOADING - USE WITH CAUTION
//          WE STRONGLY RECOMMEND YOU TO PASS THE IMAGE SIZING VIA THE
//          $properties[AMPArticle::MEDIA_SIZES_KEY] ARRAY
//
// You can check in the markup that the image fb_icon_325x325.png
// has the correct 325x325 size after enabling this option.
$properties[AMPArticle::ENABLE_DOWNLOAD_FOR_MEDIA_SIZING_KEY] = true;
// AMP has its own format for setting tracking pixels and/or analytics calls.
// You can provide a list of one or more strings containing the markup for
// the <amp-analytics> or <amp pixel> tags to the following option.
//
// See also the AMP specs for these tags:
// - https://www.ampproject.org/docs/reference/components/amp-analytics
// - https://www.ampproject.org/docs/reference/components/amp-pixel
$properties[AMPArticle::ANALYTICS_KEY] = array(
  '<amp-pixel src="http://mydomain.com/my_tracking_pixel.gif">',
  '<amp-analytics config="https://mydomain.com/analytics.config.json"></amp-analytics>'
);
// Converts it into AMP
$amp_string =
  AMPArticle::create($instant_article_string, $properties)->render();
print($amp_string);
